
[build-system]
requires = ["setuptools","setuptools-scm"]
build-backend = "setuptools.build_meta"


[project]
name = "nndp"
version = "0.0.1."


[project.optional-dependencies]
doc = [
"sphinx~=4.2.0",
"myst-parser",
"furo",
]